export const INVEST_AMOUNT = "INVEST_AMOUNT";
export const INCREASE_BALANCE = "INCREASE_BALANCE";
export const DECREASE_BALANCE = "DECREASSE_BALANCE";
export const BUY_BUSINESS = "BUY_BUSINESS";
export const SET_LAST_RUN = "SET_LAST_RUN";
export const HIRE_MANAGER = "HIRE_MANAGER";
